[package]
name = "compile-messages"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[[bin]]
name = "compile-messages"
path = "main.rs"

[dependencies]
capnpc = { path = "../../../capnpc" }

[workspace]